config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'articles#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: %i[new create]

  resources :articles, except: [:show] do
    get 'search', on: :collection
  end

  resource :search_analytic, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :pg_search,
                  against: {
                    title: 'A',
                    author: 'B',
                    body: 'C'
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  validates :title, :author, :body, presence: true
end

app/models/concerns/search_analytic_sql.rb
module SearchAnalyticSql
  def most_searched_query_sql(user)
    sql = <<~SQL
      SELECT query, COUNT(id)
      FROM search_analytics
      WHERE user_id = #{user.id}
      GROUP BY query
      ORDER BY COUNT(id) DESC;
    SQL

    ActiveRecord::Base.connection.execute(sql)
  end
end

app/models/search_analytic.rb
class SearchAnalytic < ApplicationRecord
  extend SearchAnalyticSql

  belongs_to :user

  before_save { query.downcase! }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :search_analytics

  validates :name, :email, presence: true

  before_create { email.downcase! }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include ArticlesHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in?

  def index
    initialize_redis_key

    @articles = Article.all
  end

  def search
    if params[:search].present?
      @articles = Article.pg_search(params[:search])
    else
      @articles = Article.all
    end

    track_search(params[:search])

    render :search, layout: false
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :author, :body)
  end

  def logged_in?
    redirect_to login_path if current_user.nil?
  end

  def initialize_redis_key
    $redis.set("query:user:#{@current_user.id}", '')
  end
end

app/controllers/search_analytics_controller.rb
class SearchAnalyticsController < ApplicationController
  before_action :logged_in?

  def show
    @latest_queries = SearchAnalytic.where(user: @current_user)
                                    .order(updated_at: :desc)

    @top_queries = SearchAnalytic.most_searched_query_sql(@current_user)
  end

  private

  def logged_in?
    redirect_to login_path if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)

    if @user
      log_in @user

      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    log_out unless current_user.nil?

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user

      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def track_search(query)
    return $redis.set("query:user:#{@current_user.id}", '') if query.blank?

    last_searched_query = $redis.get("query:user:#{@current_user.id}") ||
                          last_searched_query_from_db

    query.downcase!
    last_searched_query.downcase!

    # prevent logging query when words are being deleted with the backspace key
    return if last_searched_query.include?(query)

    $redis.set("query:user:#{@current_user.id}", query)

    log_data(query, last_searched_query)
  end

  def log_data(query, last_searched_query)
    if last_searched_query == '' || !query.include?(last_searched_query)
      CreateSearchAnalyticJob.perform_later(query, @current_user.id)
    else
      UpdateSearchAnalyticJob.perform_later(query, @current_user.id)
    end
  end

  def last_searched_query_from_db
    SearchAnalytic.where(user: @current_user).last.query
  end
end

app/helpers/search_analytics_helper.rb
module SearchAnalyticsHelper
  def latest_queries
    bar_chart(
      @latest_queries.limit(5).group(:updated_at, :query).count,
      title: 'Latest Queries',
      xtitle: 'Number of times searched',
      library: {
        layout: { padding: { left: 100, right: 100, bottom: 20 } },
        ticks: { precision: 0 }
      }
    )
  end

  def top_queries
    bar_chart(
      @top_queries.take(5).map(&:values),
      title: 'Top Queries',
      xtitle: 'Number of times searched',
      library: {
        layout: { padding: { left: 100, right: 100, bottom: 20 } },
        ticks: { precision: 0 }
      }
    )
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:email] = user.email
  end

  def current_user
    return unless session[:email]

    @current_user ||= User.find_by(email: session[:email])
  end

  def log_out
    session.delete(:email)

    @current_user = nil
  end
end

app/views/articles/_article.html.erb
<div class="col-sm-12 col-lg-6">
  <div class="card my-3">
    <div class="card-body">
      <h5 class="card-title"><%= article.title.capitalize() %></h5>
      <blockquote class="blockquote mb-0">
        <p class="h6 mb-3"><%= article.body %></p>
        <footer class="blockquote-footer text-right"><cite title="Source Title"><%= article.author %></cite></footer>
      </blockquote>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<% content_for :title, "Articles" %>

<h2 class="mt-5 text-center">Welcome to Latest Articles!</h2>

<div class="container" data-controller="search">
  <div class="row">
    <div class="col-md-12">
      <%= form_tag search_articles_path, method: :get, remote: true, class: 'row mt-5 justify-content-around', data: { action: "ajax:success->search#updateArticles" } do %>
        <div class="col-9 w-50">
          <%= text_field_tag :search, params[:search], class: 'form-control me-3', data: { action: "input->search#search" }, placeholder: 'start typing...' %>
          <button type="submit" data-search-target="formButton" class="btn btn-primary" hidden>Search</button>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row mt-5" data-search-target="articles">
    <%= render partial: "article", collection: @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container" style="max-width: 500px">
  <h4 class="text-center mt-5">Add a new article!</h4>
  <%= form_for(@article) do |f| %>
    <% if @article.errors.any? %>
      <div>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group mb-3">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control'%>
    </div>
    <div class="form-group mb-3">
      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control'%>
    </div>
    <div class="form-group mb-3">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control'%>
    </div>
    <div class="text-center">
      <%= f.submit 'Add Article', class: 'btn btn-primary mt-2 mb-5' %>
    </div>
  <% end %>
</div>

app/views/articles/search.html.erb
<%= render partial: "article", collection: @articles %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand navbar-light bg-light justify-content-between">
  <div class="container">
    <%= link_to 'Articles', root_path, class: 'navbar-brand' %>
    <div class="d-flex justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'New Article', new_article_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Search Insight', search_analytic_path, class: 'nav-link' %>
        </li>
        <% if @current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= @current_user.name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li> <%= link_to "Log out", logout_path, method: :delete, class: 'dropdown-item' %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/search_analytics/show.html.erb
<%= latest_queries %>
<%= top_queries %>

app/views/users/new.html.erb
<div class="container" style="max-width: 500px">
  <h4 class="text-center mt-5">Start reading Articles, sign up!</h4>
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group mb-3">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'%>
    </div>
    <div class="form-group mb-3">
      <%= f.label 'email:' %>
      <%= f.email_field :email, class: 'form-control'%>
    </div>
    <div class="text-center">
      <%= f.submit 'Sign up', class: 'btn btn-secondary mt-2 mb-5' %>
    </div>
  <% end %>
  <small>Already have an account? <%= link_to "Log in", login_path %></small>
</div>